services:
  qgis:
    build:
      context: .
      dockerfile: Dockerfile.qgis
    container_name: qgis
    environment:
      - TZ=Asia/Karachi
    ports:
      - "6080:6080"
      - "5901:5901"
    volumes:
      - ./data:/data
    shm_size: "2gb"